### ISSUE TITLE
Test and validate cluster performance

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#208]
TODO:

- Conduct tests to ensure the new cluster and its node pools are configured correctly.
- Run AI-based computational tasks to validate the performance enhancements achieved with the new setup.

**Comment by ThomasCardin** [comment]
Done using this example from https://learn.microsoft.com/en-us/azure/aks/gpu-cluster?tabs=add-ubuntu-gpu-node-pool#run-a-gpu-enabled-workload


```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: samples-tf-mnist-demo
  name: samples-tf-mnist-demo
spec:
  template:
    metadata:
      labels:
        app: samples-tf-mnist-demo
    spec:
      containers:
      - name: samples-tf-mnist-demo
        image: mcr.microsoft.com/azuredocs/samples-tf-mnist-demo:gpu
        args: ["--max_steps", "500"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           nvidia.com/gpu: 1
      restartPolicy: OnFailure
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
```
