### ISSUE TITLE
Update python lint workflow to fetch dynamically values from github secrets.

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/howard#281]
In order to enhance the workflow for testing python projects through our reusable workflow, we need a solution that fetches variables dynamically instead of listing them in the script. This will save time for everyone of having to do a PR on the github-workflows repo to add or remove env variables needed for the tests.

The following is a working example that demonstrates that we can fetch them dynamically :
```yaml 
name: test-echo-env-vars

on:
  push:
    branches:
      - main

jobs:
  test-printing-env-vars:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - run: |
        echo "$ALLMYSECRETS"
        echo "$ALLMYVARS"
      shell: bash
      env:
        ALLMYSECRETS: ${{ toJSON(secrets) }}
        ALLMYVARS: ${{ toJSON(vars) }}
```
