### ISSUE TITLE
Issue with Passing UID and GID During Docker Build and Enforcing securityContext in Kubernetes

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#305]
There is an issue with configuring the UID and GID during the build of our Dockerfile for the OpenWebUI application. Currently, if the UID and GID arguments are not specified during the build, the default values are 0, which means the application runs as root. For security reasons and to adhere to Kubernetes best practices, we need the application to respect the following securityContext:

```yaml
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
```

Relevant Dockerfile Section of openwebui:

```Dockerfile
# Initialize device type args
# use build args in the docker build command with --build-arg="BUILDARG=true"
ARG USE_CUDA=false
ARG USE_OLLAMA=false
ARG USE_CUDA_VER=cu121
ARG USE_EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
ARG USE_RERANKING_MODEL=""
ARG BUILD_HASH=dev-build
# Override at your own risk - non-root configurations are untested
ARG UID=0
ARG GID=0
...
WORKDIR /app/backend

ENV HOME /root
# Create user and group if not root
RUN if [ $UID -ne 0 ]; then \
    if [ $GID -ne 0 ]; then \
    addgroup --gid $GID app; \
    fi; \
    adduser --uid $UID --gid $GID --home $HOME --disabled-password --no-create-home app; \
    fi
...
```

Kubernetes deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:v0.3.5
          ports:
            - containerPort: 8080
          ...
```

Problem:

When the UID and GID arguments are not explicitly passed during the Docker build, the default values used are 0. This causes the container to run as root, which goes against security best practices. We want to ensure our application runs with the default values UID=1000 and GID=3000 when no arguments are provided, aligning with our Kubernetes security configuration.

Proposed Solution:
- Update the Dockerfile to set default values of UID=1000 and GID=3000 instead of 0.

- Ensure that the Kubernetes deployment's securityContext is respected regardless of the build argument configuration.
